
# Source: nova/templates/ingress-novncproxy.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: novncproxy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: novncproxy
      http:
        paths:
          - path: /
            backend:
              serviceName: nova-novncproxy
              servicePort: n-novnc
    - host: novncproxy.openstack
      http:
        paths:
          - path: /
            backend:
              serviceName: nova-novncproxy
              servicePort: n-novnc
    - host: novncproxy.openstack.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: nova-novncproxy
              servicePort: n-novnc

