# Source: mariadb/templates/monitoring/prometheus/exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-mysql-exporter
  labels:
    release_group: mariadb
    application: prometheus-mysql-exporter
    component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      release_group: mariadb
      application: prometheus-mysql-exporter
      component: exporter
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        release_group: mariadb
        application: prometheus-mysql-exporter
        component: exporter
      namespace: 
    spec:
      securityContext:
      shareProcessNamespace: true
      serviceAccountName: prometheus-mysql-exporter
      securityContext:
        runAsUser: 99
      nodeSelector:
        openstack-control-plane: enabled
      terminationGracePeriodSeconds: 30
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb"
            - name: DEPENDENCY_JOBS
              value: "exporter-create-sql-user"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
      containers:
        - name: mysql-exporter
          image: "docker.io/prom/mysqld-exporter:v0.10.0"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 99
          
          command:
            - /tmp/mysqld-exporter.sh
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: EXPORTER_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secrets
                  key: EXPORTER_USER
            - name: EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secrets
                  key: EXPORTER_PASSWORD
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secrets
                  key: DATA_SOURCE_NAME
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LISTEN_PORT
              value: "9104"
            - name: TELEMETRY_PATH
              value: "/metrics"
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: mysql-exporter-secrets
              mountPath: /etc/mysql/mysql_user.cnf
              subPath: mysql_user.cnf
              readOnly: true
            - name: mysql-exporter-bin
              mountPath: /tmp/mysqld-exporter.sh
              subPath: mysqld-exporter.sh
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: mysql-exporter-secrets
          secret:
            secretName: mysql-exporter-secrets
            defaultMode: 0444
        - name: mysql-exporter-bin
          configMap:
            name: mysql-exporter-bin
            defaultMode: 0555
