
# Source: mariadb/templates/deployment-ingress.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mariadb-mariadb-ingress
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-openstack-mariadb-ingress
subjects:
  - kind: ServiceAccount
    name: mariadb-ingress
    namespace: openstack

