
# Source: ingress/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openstack-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-cluster
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: deny";
      more_set_headers "X-Permitted-Cross-Domain-Policies: none";
      more_set_headers "Content-Security-Policy: script-src 'self'";
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: "*.openstack.svc.cluster.local"
    http:
      paths:
      - path: /
        backend:
          serviceName: ingress
          servicePort: 80

