
# Source: ingress/templates/service-ingress-metrics-exporter.yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-exporter
  labels:
    release_group: ingress
    application: ingress_exporter
    component: metrics
  annotations:
    
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
spec:
  ports:
  - name: metrics
    port: 10254
  selector:
    release_group: ingress
    application: ingress
    component: server

