
# Source: heat/templates/ingress-api.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heat
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: heat
      http:
        paths:
          - path: /
            backend:
              serviceName: heat-api
              servicePort: h-api
    - host: heat.openstack
      http:
        paths:
          - path: /
            backend:
              serviceName: heat-api
              servicePort: h-api
    - host: heat.openstack.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: heat-api
              servicePort: h-api

