
# Source: heat/templates/ingress-cfn.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloudformation
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cloudformation
      http:
        paths:
          - path: /
            backend:
              serviceName: heat-cfn
              servicePort: h-cfn
    - host: cloudformation.openstack
      http:
        paths:
          - path: /
            backend:
              serviceName: heat-cfn
              servicePort: h-cfn
    - host: cloudformation.openstack.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: heat-cfn
              servicePort: h-cfn

