
# Source: rabbitmq/templates/monitoring/prometheus/exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rabbitmq-rabbitmq-exporter"
  labels:
    release_group: rabbitmq
    application: prometheus_rabbitmq_exporter
    component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      release_group: rabbitmq
      application: prometheus_rabbitmq_exporter
      component: exporter
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        release_group: rabbitmq
        application: prometheus_rabbitmq_exporter
        component: exporter
      namespace: 
    spec:
      securityContext:
        runAsUser: 65534
      serviceAccountName: "rabbitmq-rabbitmq-exporter"
      nodeSelector:
        openstack-control-plane: "enabled"
      terminationGracePeriodSeconds: 30
      initContainers:
        
        - name: init
          image: "deploy001:5000/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:rabbitmq"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
      containers:
        - name: rabbitmq-exporter
          image: "deploy001:5000/kbudde/rabbitmq-exporter:v0.21.0"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - name: metrics
              containerPort: 9095
          env:
          - name: RABBIT_URL
            value: http://rabbitmq.openstack.svc.cluster.local:15672
          - name: RABBIT_USER
            value: "rabbitmq"
          - name: RABBIT_PASSWORD
            value: "password"
          - name: RABBIT_CAPABILITIES
            value: "no_sort"
          - name: PUBLISH_PORT
            value: "9095"
          - name: LOG_LEVEL
            value: "info"
          - name: SKIPVERIFY
            value: "1"

