
# Source: ingress/templates/service-error.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    release_group: ingress
    application: ingress
    component: error-pages
  name: ingress-error-pages
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    release_group: ingress
    application: ingress
    component: error-pages

