# Source: taco-watcher/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taco-watcher
  labels:
    app.kubernetes.io/name: taco-watcher
    helm.sh/chart: taco-watcher-0.1.0
    app.kubernetes.io/instance: taco-watcher
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taco-watcher
      app.kubernetes.io/instance: taco-watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taco-watcher
        app.kubernetes.io/instance: taco-watcher
    spec:
#      hostNetwork: true
      containers:
      - name: watcher
        image: "sktdev/taco-watcher:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 32000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 32000 
        readinessProbe:
          httpGet:
            path: /
            port: 32000 
        volumeMounts:
        - name: conf
          mountPath: /home/tacomo/tacomo-webserver/conf/tacomo.conf
          subPath: tacomo.conf
        - name: conf
          mountPath: /home/tacomo/tacomo-webserver/conf/loggingfilter.json
          subPath: loggingfilter.json
        - name: conf
          mountPath: /home/tacomo/tacomo-webserver/conf/prometheusrule.json 
          subPath: prometheusrule.json 
        - name: sql
          mountPath: /home/tacomo/tacomo-webserver/sql/tacomodb_1.sql
          subPath: tacomodb_1.sql
        - name: db-volume
          mountPath: /home/tacomo/tacomo-webserver/dbdata
        - name: log-volume
          mountPath: /home/tacomo/tacomo-webserver/logs
      volumes:
      - name: conf
        configMap:
          name: taco-watcher
          items:
          - key: tacomo.conf
            path: tacomo.conf
          - key: loggingfilter.json
            path: loggingfilter.json
          - key: prometheusrule.json 
            path: prometheusrule.json 
      - name: sql
        configMap:
          name: taco-watcher
          items:
          - key: tacomodb_1.sql
            path: tacomodb_1.sql
      - name: db-volume
        persistentVolumeClaim:
          claimName: taco-watcher-pvc
      - name: log-volume
        hostPath:
          path: /tmp
          type: Directory
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
