
# Source: ceph-provisioners/templates/configmap-etc-client.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-etc
data:
  ceph.conf: |
    [global]
    cephx = true
    cephx_cluster_require_signatures = true
    cephx_require_signatures = false
    cephx_service_require_signatures = false
    debug_ms = 0/0
    mon_addr = :6789
    mon_host = TACO_MON_HOST
    objecter_inflight_op_bytes = 1073741824
    objecter_inflight_ops = 10240
    [osd]
    cluster_network = 192.168.0.0/16
    ms_bind_port_max = 7100
    ms_bind_port_min = 6800
    osd_max_object_name_len = 256
    osd_mkfs_options_xfs = -f -i size=2048
    osd_mkfs_type = xfs
    public_network = 192.168.0.0/16

