
# Source: prometheus-openstack-exporter/templates/deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-openstack-exporter-prometheus-openstack-exporter
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-openstack-exporter-openstack-prometheus-openstack-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-openstack-exporter
    namespace: openstack

