
# Source: prometheus-openstack-exporter/templates/job-ks-user.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-openstack-exporter-prometheus-openstack-exporter-ks-user
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-openstack-exporter-openstack-prometheus-openstack-exporter-ks-user
subjects:
  - kind: ServiceAccount
    name: prometheus-openstack-exporter-ks-user
    namespace: openstack

