
# Source: horizon/templates/ingress-api.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: horizon
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: horizon
      http:
        paths:
          - path: /
            backend:
              serviceName: horizon-int
              servicePort: web
    - host: horizon.openstack
      http:
        paths:
          - path: /
            backend:
              serviceName: horizon-int
              servicePort: web
    - host: horizon.openstack.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: horizon-int
              servicePort: web

