
# Source: glance/templates/ingress-api.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: glance
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 102400M
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: glance
      http:
        paths:
          - path: /
            backend:
              serviceName: glance-api
              servicePort: g-api
    - host: glance.openstack
      http:
        paths:
          - path: /
            backend:
              serviceName: glance-api
              servicePort: g-api
    - host: glance.openstack.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: glance-api
              servicePort: g-api

