# Source: ironic/templates/deployment-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic-api
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: ironic
    application: ironic
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      release_group: ironic
      application: ironic
      component: api
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        release_group: ironic
        application: ironic
        component: api
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "b5523a4bdbb1495d25171c6656a18a5e927c23ba7fb3e63cbb00a0ab5c321f55"
        configmap-etc-hash: "fb03361f9975f45aa54a65b5ed5e61eb5daf1a3b4b858d547cb957b9e677e009"
    spec:
      serviceAccountName: ironic-api
      affinity:
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: release_group
                    operator: In
                    values:
                    - ironic
                  - key: application
                    operator: In
                    values:
                    - ironic
                  - key: component
                    operator: In
                    values:
                    - api
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        openstack-control-plane: enabled
      terminationGracePeriodSeconds: 30
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb,openstack:keystone-api,openstack:rabbitmq"
            - name: DEPENDENCY_JOBS
              value: "ironic-db-sync,ironic-ks-user,ironic-ks-endpoints,ironic-manage-cleaning-network,ironic-rabbit-init"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null
        - name: ironic-retrive-cleaning-net
          image: "docker.io/openstackhelm/heat:ocata-ubuntu_xenial"
          imagePullPolicy: IfNotPresent
          
          env:            
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_AUTH_URL
            - name: OS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_REGION_NAME
            - name: OS_INTERFACE
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_INTERFACE
            - name: OS_PROJECT_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_PROJECT_DOMAIN_NAME
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_PROJECT_NAME
            - name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_USER_DOMAIN_NAME
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_USERNAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_PASSWORD
            - name: OS_DEFAULT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ironic-keystone-user
                  key: OS_DEFAULT_DOMAIN
            - name: device
              value: "eth1"
            - name: neutron_network_name
              value: "baremetal-net"
            - name: neutron_provider_network
              value: "baremetal"
            - name: neutron_subnet_alloc_end
              value: "192.168.0.150"
            - name: neutron_subnet_alloc_start
              value: "192.168.0.100"
            - name: neutron_subnet_cidr
              value: "192.168.0.0/24"
            - name: neutron_subnet_dns_nameserver
              value: "8.8.8.8"
            - name: neutron_subnet_gateway
              value: "192.168.0.1"
            - name: neutron_subnet_name
              value: "baremetal-subnet"
            
          command:
            - /tmp/retreive-cleaning-network.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: ironic-bin
              mountPath: /tmp/retreive-cleaning-network.sh
              subPath: retreive-cleaning-network.sh
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared
      containers:
        - name: ironic-api
          image: "docker.io/openstackhelm/ironic:ocata-ubuntu_xenial"
          imagePullPolicy: IfNotPresent
          
          command:
            - /tmp/ironic-api.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/ironic-api.sh
                  - stop
          ports:
            - containerPort: 6385
          readinessProbe:
            tcpSocket:
              port: 6385
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: ironic-bin
              mountPath: /tmp/ironic-api.sh
              subPath: ironic-api.sh
              readOnly: true
            - name: ironic-etc
              mountPath: /etc/ironic/ironic.conf
              subPath: ironic.conf
              readOnly: true
            - name: ironic-etc
              mountPath: /etc/ironic/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: ironic-etc
              mountPath: /etc/ironic/policy.json
              subPath: policy.json
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: ironic-bin
          configMap:
            name: ironic-bin
            defaultMode: 0555
        - name: ironic-etc
          secret:
            secretName: ironic-etc
            defaultMode: 0444
        - name: pod-shared
          emptyDir: {}
