
# Source: ironic/templates/ingress-api.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: baremetal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: baremetal
      http:
        paths:
          - path: /
            backend:
              serviceName: ironic-api
              servicePort: m-api
    - host: baremetal.openstack
      http:
        paths:
          - path: /
            backend:
              serviceName: ironic-api
              servicePort: m-api
    - host: baremetal.openstack.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: ironic-api
              servicePort: m-api

